### ISSUE TITLE
Copy Plans doesn't work with standard plans.

### ISSUE THREAD

**Issue by ghost** [alandariva/RimworldMorePlanning#5]
When I try to copy plans that I made with the game's standard Plan feature (in the Orders menu), it fails with this message: No planning designations were found in the selection.

The same thing happens when I try to copy plans that were created with other mods (e.g. Blueprints).

Basically, this mod behaves as if it doesn't work with real plan markers at all, but fakes it by creating its own lookalikes and ignoring everything else. It would be a lot more useful if it was compatible with the real thing.

**Comment by alandariva** [comment]
As it was needed to record a color I created another plan marker and forgot to test the copy feature. Thanks for your submit.

This was fixed with version 5.0.0
